### ISSUE TITLE
Integrate basic Twitter search API calling

### ISSUE THREAD

**Issue by norrishd** [utmittal/pyramidal-action-party#2]

**Comment by norrishd** [comment]
Just copied across my existing file from previous personal experimentation

**Comment by utmittal** [comment]
I would love to convert this to a class with relevant methods and what not. I could get on it later in the week

**Comment by norrishd** [comment]
To add to my Slack comment - you can either make a new issue for re-structuring my initial version, or re-assign yourself to this card, take me off it and move it back to the 'Doing' list

**Comment by norrishd** [comment]
Utkarsh too slow. Moving this along and made a new card for if he wants to do at some point.
